spring:
  application:
    name: Database
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    password: postgres
    username: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: bookings
        hbm2ddl:
          auto: update